services:
    db:
        image: postgres
        restart: always
        ports:
            - 5433:5433
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: admin
            POSTGRES_DB: main_db
        volumes:
            - pgdata:/var/lib/postgresql/data


volumes:
    pgdata: